image: node:10.0.0

stages:
  - npm
  - test
  - deploy

npm:
  stage: npm
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm test

codecov:
  stage: deploy
  script:
    - npm run cov:html
    - npm run cov:send
  only:
    - master
