image: node:10.0.0

stages:
  - npm
  - test
  - deploy

npm:
  stage: npm
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm test
  artifacts:
    paths:
      - coverage/
      - .nyc_output/

codecov:
  stage: deploy
  dependencies:
    - npm
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - npm
    - test
  script:
    - npm run cov:html
    - npm run cov:send
  only:
    - master
